### PR TITLE
✨ NEW: include .gitlab-ci.yml for GitLab users

### PR DESCRIPTION
**Pull request by slemonide**
This solves issue #7.

### CODE REVIEW

**Comment by TomasBeuzen** [comment]
@slemonide - thanks for this PR! I'm not familiar with GitLab and did wonder if GitLab users would be using this project - which is currently very much GitHub-inclined. 

I've made a few changes, most notably, I've renamed the "include_github_actions" cookiecutter option to:

```
Select include_ci:
1 - github
2 - gitlab
3 - no
```

In future, I'd like to make the interface more platform-agnostic. I'll create an issue about that. Anyway feel free to run an eye over these changes - but otherwise LGTM.

**Comment by slemonide** [comment]
https://github.com/slemonide/cookiecutter-jupyter-book/blob/845770037be40b84c1a393da10c88607e2a58492/%7B%7Bcookiecutter.book_slug%7D%7D/%7B%7Bcookiecutter.book_slug%7D%7D/_config.yml#L45

This probably also should be changed. But sphinx-book-theme would have to be modified first to support non-github locations.

This will need to be changed too:
https://github.com/executablebooks/cookiecutter-jupyter-book/blob/845770037be40b84c1a393da10c88607e2a58492/hooks/post_gen_project.py#L79

**Comment by slemonide** [comment]
But that should probably be a different issue/pull request.

**Comment by slemonide** [comment]
There probably also should be some tests to verify that builds with this .github-ci.yml file succeed.

**Comment by TomasBeuzen** [comment]
I have a few ideas for the above - I'll make some changes within the next week or so when I get a chance

**Comment by TomasBeuzen** [comment]
I've opened #10 to address some of the concerns raised in this PR but will merge this in the morning

**Pull request merged**
